version: 0.0
os: linux
files:
  - source: /index.html
    destination: /var/www/html/  # Change this path if necessary

hooks:
  AfterInstall:
    - location: scripts/restart_nginx.sh
      timeout: 60
      runas: root
